/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rftecnicos
 */
public class Monedas extends javax.swing.JFrame {

    /**
     * Creates new form Monedas
     */
    public Monedas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        imagendado2 = new javax.swing.JLabel();
        imagendado1 = new javax.swing.JLabel();
        juego = new javax.swing.JLabel();
        star = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagendado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/dado2.PNG"))); // NOI18N
        getContentPane().add(imagendado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, 200));

        imagendado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculo/dado1.PNG"))); // NOI18N
        getContentPane().add(imagendado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 200));

        juego.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        juego.setForeground(new java.awt.Color(255, 255, 255));
        juego.setText("JUEGO DE DADOS");
        getContentPane().add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        star.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        star.setText("STAR");
        star.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starMouseClicked(evt);
            }
        });
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });
        getContentPane().add(star, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 140, -1));

        salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Para ganar tienes que sacar siete");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo7.jpg"))); // NOI18N
        fondo2.setText("jLabel1");
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed

        Random rnd = new Random();
        int dado1 = 0;
        dado1 = ((int)(rnd.nextDouble()*6));
        int dado2 = 0;
        dado2 = ((int)(rnd.nextDouble()*6));
        
          if(dado1==0){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado1.png")));
        } else if(dado1==1){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado2.png")));
        } else if(dado1==2){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado3.png")));
        } else if(dado1==3){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado4.png")));
        } else if(dado1==4){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado5.png")));
        } else if(dado1==5){
           imagendado1.setIcon(new ImageIcon(getClass().getResource("dado6.png")));
        }
        
          if(dado2==0){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado1.png")));
        } else if(dado2==1){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado2.png")));
        } else if(dado2==2){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado3.png")));
        } else if(dado2==3){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado4.png")));
        } else if(dado2==4){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado5.png")));
        } else if(dado2==5){
           imagendado2.setIcon(new ImageIcon(getClass().getResource("dado6.png")));
        }

    }//GEN-LAST:event_starActionPerformed

    private void starMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_starMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_starMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel imagendado1;
    private javax.swing.JLabel imagendado2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel juego;
    private javax.swing.JButton salir;
    private javax.swing.JButton star;
    // End of variables declaration//GEN-END:variables
}
